import Head from 'next/head'
import type { NextPage } from 'next'
import { useTranslation } from 'i18next-config';

const Home: NextPage = () => {
  const { t } = useTranslation('common')

  return (
    <div>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='app btn-primary'>
        <h1>
        {t('app_name')}
        </h1>
      </main>
    </div>
  )
}

export default Home
